name: Convert Markdown to DOCX

inputs:
  input_file:
    description: 'Markdown input file'
    required: true
  output_file:
    description: 'Output DOCX file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile Java class with package
      run: |
        javac -d out src/com/github/roche/capt/report/MarkdownToDocxConverter.java
      shell: bash

    - name: Run converter
      run: |
        java -cp out com.github.roche.capt.report.MarkdownToDocxConverter "${{ inputs.input_file }}" "${{ inputs.output_file }}"
      shell: bash
