name: Convert Markdown to DOCX

inputs:
  input_file:
    description: 'Markdown input file'
    required: true
  output_file:
    description: 'Output DOCX file'
    required: true

runs:
  using: "composite"
  steps:  
      - name: Build with Maven
      run: |
        cd capt-report
        mvn clean compile
      shell: bash
      
    - name: Run converter
      run: |
        cd capt-report
        mvn exec:java -Dexec.mainClass="com.github.roche.capt.report.MarkdownToDocxConverter" -Dexec.args="${{ inputs.input_file }} ${{ inputs.output_file }}"
      shell: bash