name: Convert Markdown to DOCX

inputs:
  input_file:
    description: 'Markdown input file'
    required: true
  output_file:
    description: 'Output DOCX file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile Java class
      run: javac src/MarkdownToDocxConverter.java
      shell: bash

    - name: Run converter
      run: java -cp src MarkdownToDocxConverter "${{ inputs.input_file }}" "${{ inputs.output_file }}"
      shell: bash
