name: Convert Markdown to DOCX

inputs:
  input_file:
    description: 'Markdown input file'
    required: true
  output_file:
    description: 'Output DOCX file'
    required: true

runs:
  using: "composite"
  steps:
    - name: List contents of capt-report directory
      run: ls -R capt-report
      shell: bash
      
    - name: Check Java file exists
      run: ls -l capt-report/src/main/java/com/github/roche/capt/report/MarkdownToDocxConverter.java
      shell: bash
      
    - name: Compile Java class with package
      run: |
        javac -d out src/main/java/com/github/roche/capt/report/MarkdownToDocxConverter.java
      shell: bash

    - name: Run converter
      run: |
        java -cp out com.github.roche.capt.report.MarkdownToDocxConverter "${{ inputs.input_file }}" "${{ inputs.output_file }}"
      shell: bash
